### ISSUE TITLE
Zypak does not work with Webex

### ISSUE THREAD

**Issue by chrispoupart** [chrispoupart/flatpak-com.cisco.Webex#1]
Waiting on this bug to be resolved: https://github.com/refi64/zypak/issues/14

**Comment by vincentbernat** [comment]
While not released, I am able to make it work with the webex branch and the following manifest:

```yaml
app-id: com.cisco.Webex
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
command: webex
tags:
  - proprietary
finish-args:
  - "--share=ipc"
  - "--socket=x11"
  - "--socket=pulseaudio"
  - "--share=network"
  - "--device=all"
  - "--talk-name=org.freedesktop.Notifications"
  - "--talk-name=org.freedesktop.secrets"
modules:
  - name: libsecret
    buildsystem: meson
    config-opts:
      - "-Dmanpage=false"
      - "-Dvapi=false"
      - "-Dgtk_doc=false"
    cleanup:
      - "/bin"
      - "/include"
      - "/lib/pkgconfig"
      - "/share/gir-1.0"
      - "/share/man"
    sources:
    - type: archive
      url: https://download.gnome.org/sources/libsecret/0.19/libsecret-0.19.1.tar.xz
      sha256: 8583e10179456ae2c83075d95455f156dc08db6278b32bf4bd61819335a30e3a 
  - name: zypak
    sources:
      - type: git
        url: https://github.com/refi64/zypak
        branch: webex
  - name: webex
    buildsystem: simple
    build-commands:
      - ar x Webex.deb
      - tar xf data.tar.xz
      - cp -r opt/Webex $FLATPAK_DEST/Webex
      - rm $FLATPAK_DEST/Webex/lib/libstdc++.so.6
      - chmod -R a-s,go+rX,go-w $FLATPAK_DEST/Webex
      - install -Dm755 webex.sh $FLATPAK_DEST/bin/webex
      - touch $FLATPAK_DEST/Webex/deb.dat
    sources:
      - type: script
        dest-filename: webex.sh
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - export ZYPAK_QUIRKS=webex-trampoline
          - exec zypak-wrapper /app/Webex/bin/CiscoCollabHost "$@"
      - type: file
        only-arches:
          - x86_64
        url: https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb
        sha256: c74aefeaea07610d6898fbf9d78a1be22e555743a58014b383d1a260622146db
        size: 300343322
```

I have pinged the maintainer to merge the branch into master. Sound and webcam now works for me.
